ALTER TABLE file_versions
  ADD COLUMN IF NOT EXISTS mtime_ms BIGINT,
  ADD COLUMN IF NOT EXISTS ctime_ms BIGINT;

ALTER TABLE change_events
  ADD COLUMN IF NOT EXISTS mtime_ms BIGINT,
  ADD COLUMN IF NOT EXISTS ctime_ms BIGINT;
