#!/usr/bin/env bash
set -euo pipefail

BASE_URL="${BASE_URL:-http://localhost:3000/api/v1}"
EMAIL="${EMAIL:-admin@example.com}"
PASSWORD="${PASSWORD:-admin123456}"

REPORT_DIR="${REPORT_DIR:-reports/perf}"
RUN_TAG="${RUN_TAG:-$(date -u +%Y%m%dT%H%M%SZ)}"

BASELINE_USERS="${PERF_BASELINE_USERS:-10}"
BASELINE_DURATION_SEC="${PERF_BASELINE_DURATION_SEC:-60}"
BASELINE_THINK_TIME_MS="${PERF_BASELINE_THINK_TIME_MS:-120}"
BASELINE_MAX_OVERALL_ERROR_RATE="${BASELINE_MAX_OVERALL_ERROR_RATE:-0.05}"
BASELINE_MAX_COMMIT_ERROR_RATE="${BASELINE_MAX_COMMIT_ERROR_RATE:-0.05}"

WEAK_USERS="${PERF_WEAK_USERS:-8}"
WEAK_DURATION_SEC="${PERF_WEAK_DURATION_SEC:-60}"
WEAK_THINK_TIME_MS="${PERF_WEAK_THINK_TIME_MS:-180}"
WEAK_DELAY_MIN_MS="${PERF_WEAK_DELAY_MIN_MS:-300}"
WEAK_DELAY_MAX_MS="${PERF_WEAK_DELAY_MAX_MS:-800}"
WEAK_TIMEOUT_RATE="${PERF_WEAK_TIMEOUT_RATE:-0.20}"
WEAK_DROP_RATE="${PERF_WEAK_DROP_RATE:-0.05}"
WEAK_MAX_OVERALL_ERROR_RATE="${WEAK_MAX_OVERALL_ERROR_RATE:-0.30}"
WEAK_MAX_COMMIT_ERROR_RATE="${WEAK_MAX_COMMIT_ERROR_RATE:-0.20}"

mkdir -p "$REPORT_DIR"

baseline_report="$REPORT_DIR/${RUN_TAG}-concurrency-baseline.json"
weak_report="$REPORT_DIR/${RUN_TAG}-weak-network.json"
summary_md="$REPORT_DIR/${RUN_TAG}-summary.md"

status=0

if ! BASE_URL="$BASE_URL" EMAIL="$EMAIL" PASSWORD="$PASSWORD" \
  SCENARIO="concurrency-baseline" WEAK_MODE=0 \
  USERS="$BASELINE_USERS" DURATION_SEC="$BASELINE_DURATION_SEC" THINK_TIME_MS="$BASELINE_THINK_TIME_MS" \
  MAX_OVERALL_ERROR_RATE="$BASELINE_MAX_OVERALL_ERROR_RATE" MAX_COMMIT_ERROR_RATE="$BASELINE_MAX_COMMIT_ERROR_RATE" \
  REPORT_FILE="$baseline_report" \
  node scripts/load-sync-api.mjs; then
  status=1
fi

if ! BASE_URL="$BASE_URL" EMAIL="$EMAIL" PASSWORD="$PASSWORD" \
  SCENARIO="weak-network" WEAK_MODE=1 \
  USERS="$WEAK_USERS" DURATION_SEC="$WEAK_DURATION_SEC" THINK_TIME_MS="$WEAK_THINK_TIME_MS" \
  WEAK_DELAY_MIN_MS="$WEAK_DELAY_MIN_MS" WEAK_DELAY_MAX_MS="$WEAK_DELAY_MAX_MS" \
  WEAK_TIMEOUT_RATE="$WEAK_TIMEOUT_RATE" WEAK_DROP_RATE="$WEAK_DROP_RATE" \
  MAX_OVERALL_ERROR_RATE="$WEAK_MAX_OVERALL_ERROR_RATE" MAX_COMMIT_ERROR_RATE="$WEAK_MAX_COMMIT_ERROR_RATE" \
  REPORT_FILE="$weak_report" \
  node scripts/load-sync-api.mjs; then
  status=1
fi

node scripts/generate-perf-summary.mjs --out "$summary_md" "$baseline_report" "$weak_report"

echo "PERF_BASELINE_REPORT=$baseline_report"
echo "PERF_WEAK_REPORT=$weak_report"
echo "PERF_SUMMARY_REPORT=$summary_md"

exit "$status"
